export const APIS = [
  {
    id: "stripe",
    name: "Stripe",
    logoColor: "#635BFF",
    category: "Payments",
    verified: true,
    tagline: "Financial infrastructure for the internet",
    description: "Stripe's suite of APIs powers online payment processing, billing, card issuing, payouts, and business operations globally. Renowned for setting the industry standard for developer experience.",
    docsUrl: "https://stripe.com/docs/api",
    githubUrl: "https://github.com/stripe/stripe-node",
    openapiUrl: "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json",
    postmanUrl: "https://www.postman.com/stripe-api",
    sandboxAvailable: true,
    baseUrl: "https://api.stripe.com",
    vitals: {
      healthScore: 99.9,
      latency: 84, // ms
      uptime: 99.99, // %
      docsScore: 9.8,
      sdkScore: 9.6,
      communityScore: 9.5,
      githubActivity: "High (24 commits/week)",
      status: "Operational",
      responseTime: "84ms (p95: 142ms)",
      popularity: 98,
      security: "PCI-DSS L1, SOC2",
      community: "24.5k Github Stars, 120k Discord Devs",
      aiConfidence: 98,
      lastUpdated: "2 hours ago",
      commitsCount: "14,821",
      version: "2024-06-20",
      rateLimit: "100 requests/sec",
      authType: "Bearer Token (API Key)",
      responseFormat: "JSON",
      difficulty: "Easy"
    },
    dna: {
      similarities: [
        { target: "razorpay", percentage: 89, reason: "REST patterns, payment flows & webhook schemas match closely." },
        { target: "paypal", percentage: 67, reason: "Both handle merchant ledger balances, but checkout state-machines differ." }
      ],
      radar: {
        auth: 95,
        performance: 92,
        docs: 98,
        dx: 97,
        pricing: 85
      },
      migrationComplexity: "Low (standard integration mapping exists)",
      breakingChangesPredictor: 1.2, // % chance in next 6 months
      evolutionTimeline: [
        { date: "June 2026", event: "Added native UPI Auto-pay schemas." },
        { date: "March 2026", event: "Deprecated legacy Charge schemas in favor of PaymentIntents." },
        { date: "Jan 2026", event: "Upgraded Webhook cryptography header validation." }
      ],
      sdkMaturity: "Platinum (official SDKs in 9 languages with autogenerated type guards)",
      deprecationRisk: "Negligible (minimum 3-year migration windows for legacy endpoints)"
    },
    painIndex: {
      githubIssues: 42,
      stackoverflowQuestions: 1420,
      discordMentions: 340,
      redditActivity: "Low (highly structured subreddits)",
      learningDifficulty: "Very Low",
      topComplaints: [
        "Webhook retries can occasionally cause duplication if not properly idempotency-keyed.",
        "Testing corner cases for regional authentication protocols (like 3D Secure 2.0) requires multi-step mock headers."
      ],
      confusingEndpoints: [
        { path: "/v1/payment_intents/:id/confirm", complexity: "Requires payment_method or return_url parameters depending on payment state." }
      ],
      commonErrors: [
        {
          code: "resource_missing",
          description: "Occurs when a specified ID (e.g. customer ID, price ID) does not exist in the live or test mode system.",
          remedy: "Cross-reference test keys vs live keys. Resources created in test mode do not exist in live mode."
        },
        {
          code: "parameter_missing",
          description: "A required request parameter was omitted from the payload structure.",
          remedy: "Check active documentation schema for required sub-keys. Ensure 'currency' is specified with amount."
        }
      ]
    },
    endpoints: [
      {
        path: "/v1/payment_intents",
        method: "POST",
        description: "Creates a PaymentIntent object. Use this to track a customer's payment lifecycle from creation through completion.",
        authRequired: true,
        rateLimit: "100 req/sec",
        params: [
          { name: "amount", type: "integer", required: true, description: "A positive integer representing how much to charge in the smallest currency unit (e.g., 1000 for $10.00)." },
          { name: "currency", type: "string", required: true, description: "Three-letter ISO currency code, in lowercase (e.g., usd, eur)." },
          { name: "payment_method_types", type: "array", required: false, description: "List of payment method types to display (defaults to ['card'])." }
        ],
        codeExamples: {
          curl: "curl https://api.stripe.com/v1/payment_intents \\\n  -u sk_test_51Nz...: \\\n  -d amount=2000 \\\n  -d currency=usd",
          python: "import stripe\nstripe.api_key = \"sk_test_51Nz...\"\n\nintent = stripe.PaymentIntent.create(\n  amount=2000,\n  currency=\"usd\",\n)",
          javascript: "const stripe = require('stripe')('sk_test_51Nz...');\n\nconst paymentIntent = await stripe.paymentIntents.create({\n  amount: 2000,\n  currency: 'usd',\n});",
          go: "package main\nimport (\n  \"github.com/stripe/stripe-go/v72\"\n  \"github.com/stripe/stripe-go/v72/paymentintent\"\n)\n\nfunc main() {\n  stripe.Key = \"sk_test_51Nz...\"\n  params := &stripe.PaymentIntentParams{\n    Amount:   stripe.Int64(2000),\n    Currency: stripe.String(string(stripe.CurrencyUSD)),\n  }\n  result, _ := paymentintent.New(params)\n}"
        },
        response: {
          status: 200,
          body: {
            id: "pi_3M3n9W2eZvKYlo2C1x9Q4ZJ9",
            object: "payment_intent",
            amount: 2000,
            currency: "usd",
            status: "requires_payment_method",
            client_secret: "pi_3M3n9W2eZvKYlo2C1x9Q4ZJ9_secret_XYZ123",
            created: 1716912345
          }
        }
      },
      {
        path: "/v1/customers",
        method: "POST",
        description: "Creates a new customer object, enabling storage of card profiles and tracking subscriptions.",
        authRequired: true,
        rateLimit: "100 req/sec",
        params: [
          { name: "email", type: "string", required: false, description: "The customer's email address, useful for receipt routing." },
          { name: "name", type: "string", required: false, description: "The customer's full name or billing entity name." },
          { name: "description", type: "string", required: false, description: "An arbitrary string attached to the object." }
        ],
        codeExamples: {
          curl: "curl https://api.stripe.com/v1/customers \\\n  -u sk_test_51Nz...: \\\n  -d email=\"dev@apipedia.dev\" \\\n  -d name=\"APIpedia Dev\"",
          python: "import stripe\nstripe.api_key = \"sk_test_51Nz...\"\n\ncustomer = stripe.Customer.create(\n  email=\"dev@apipedia.dev\",\n  name=\"APIpedia Dev\"\n)",
          javascript: "const stripe = require('stripe')('sk_test_51Nz...');\n\nconst customer = await stripe.customers.create({\n  email: 'dev@apipedia.dev',\n  name: 'APIpedia Dev'\n});",
          go: "package main\nimport (\n  \"github.com/stripe/stripe-go/v72\"\n  \"github.com/stripe/stripe-go/v72/customer\"\n)\n\nfunc main() {\n  stripe.Key = \"sk_test_51Nz...\"\n  params := &stripe.CustomerParams{\n    Email: stripe.String(\"dev@apipedia.dev\"),\n    Name:  stripe.String(\"APIpedia Dev\"),\n  }\n  result, _ := customer.New(params)\n}"
        },
        response: {
          status: 200,
          body: {
            id: "cus_OnM78Hn29A2n",
            object: "customer",
            email: "dev@apipedia.dev",
            name: "APIpedia Dev",
            balance: 0,
            created: 1716912380
          }
        }
      }
    ],
    recipes: [
      {
        title: "Next.js Webhook Signatures Handler",
        framework: "Next.js",
        duration: "5 mins",
        difficulty: "Easy",
        diagram: `
+----------------+      POST /api/webhooks      +--------------------+
|  Stripe Cloud  | ---------------------------> | Next.js API Route  |
+----------------+                              +--------------------+
                                                          |
                                           validate signature w/ webhook secret
                                                          v
                                               trigger database upsert
`,
        code: `import { NextResponse } from 'next/server';
import stripe from '@/lib/stripe';

export async function POST(req) {
  const body = await req.text();
  const signature = req.headers.get('stripe-signature');

  let event;
  try {
    event = stripe.webhooks.constructEvent(
      body,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET
    );
  } catch (err) {
    return NextResponse.json({ error: 'Webhook signature validation failed' }, { status: 400 });
  }

  if (event.type === 'invoice.payment_succeeded') {
    const session = event.data.object;
    // Perform database operations to activate user subscription
  }

  return NextResponse.json({ received: true });
}`
      }
    ],
    paths: [
      { id: "15m", name: "Accept a Card Payment", progress: 0, steps: ["Generate API keys", "Setup stripe.js checkout component", "Construct webhook verification handler"] },
      { id: "45m", name: "SaaS Subscription Billing", progress: 0, steps: ["Create products & prices in dashboard", "Integrate customer portal", "Handle invoice payment failures"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [88, 86, 84, 82, 85, 84, 84],
      uptime: [99.99, 100, 99.98, 99.99, 99.99, 100, 99.99],
      errors: [0.02, 0.01, 0.05, 0.01, 0.02, 0.02, 0.01]
    }
  },
  {
    id: "openai",
    name: "OpenAI",
    logoColor: "#10A37F",
    category: "AI",
    verified: true,
    tagline: "Artificial Intelligence model access via REST APIs",
    description: "Provide endpoints for advanced language models, code generation, reasoning engines, and image analysis tools (GPT-4o, o1, DALL-E). Powering next-gen conversational and reasoning UI layers.",
    docsUrl: "https://platform.openai.com/docs/api-reference",
    githubUrl: "https://github.com/openai/openai-node",
    openapiUrl: "https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml",
    postmanUrl: "https://www.postman.com/openai-api",
    sandboxAvailable: false,
    baseUrl: "https://api.openai.com",
    vitals: {
      healthScore: 98.4,
      latency: 340, // ms
      uptime: 99.85, // %
      docsScore: 8.8,
      sdkScore: 9.2,
      communityScore: 9.9,
      githubActivity: "Very High (42 commits/week)",
      status: "Operational",
      responseTime: "340ms (varies by tokens)",
      popularity: 99,
      security: "SOC2 Type II, HIPAA compliant pipelines",
      community: "38.2k Github Stars, 420k Discord Devs",
      aiConfidence: 96,
      lastUpdated: "5 minutes ago",
      commitsCount: "8,924",
      version: "v1 (pinned updates)",
      rateLimit: "10,000 requests/min (Tier 3)",
      authType: "Bearer Token",
      responseFormat: "JSON",
      difficulty: "Medium"
    },
    dna: {
      similarities: [
        { target: "anthropic", percentage: 91, reason: "Identical ChatCompletions roles (system/user/assistant) and stream architectures." }
      ],
      radar: {
        auth: 90,
        performance: 75,
        docs: 92,
        dx: 94,
        pricing: 80
      },
      migrationComplexity: "Medium (requires prompt alignment & schema validation)",
      breakingChangesPredictor: 4.8,
      evolutionTimeline: [
        { date: "July 2026", event: "Released GPT-4o-mini structured schema outputs." },
        { date: "May 2026", event: "Deprecated legacy text-davinci completions endpoints." },
        { date: "Jan 2026", event: "Standardized tool_calls array responses for function calling." }
      ],
      sdkMaturity: "Gold (Official client wrappers in Node, Python, and community Go libraries)",
      deprecationRisk: "Moderate (Fast pacing leads to model deprecation schedules every 6 months)"
    },
    painIndex: {
      githubIssues: 184,
      stackoverflowQuestions: 5410,
      discordMentions: 980,
      redditActivity: "High (r/openai, r/learnmachinelearning)",
      learningDifficulty: "Medium",
      topComplaints: [
        "Strict rate limits on tiers can throw unexpected 429 status codes without warning.",
        "Structured outputs (JSON Schema mode) occasionally reject inputs if prompts are too complex or vague."
      ],
      confusingEndpoints: [
        { path: "/v1/chat/completions", complexity: "The payload structure combines tools, tool_choice, temperature, and response_format. Hard to type check." }
      ],
      commonErrors: [
        {
          code: "rate_limit_exceeded",
          description: "You have sent too many tokens or requests in a given period for your account tier.",
          remedy: "Implement exponential backoff retry algorithms or request a limit tier increase via billing dashboard."
        },
        {
          code: "invalid_request_error",
          description: "The request body failed token length limits or contains unsupported JSON parameters.",
          remedy: "Calculate tokens locally using tiktoken library before sending. Remove null or empty keys."
        }
      ]
    },
    endpoints: [
      {
        path: "/v1/chat/completions",
        method: "POST",
        description: "Creates a model response for the given chat conversation containing system, user, or tool instructions.",
        authRequired: true,
        rateLimit: "10,000 RPM",
        params: [
          { name: "model", type: "string", required: true, description: "ID of the model to use (e.g., gpt-4o, gpt-3.5-turbo)." },
          { name: "messages", type: "array", required: true, description: "A list of messages comprising the conversation history." },
          { name: "temperature", type: "number", required: false, description: "What sampling temperature to use, between 0 and 2 (defaults to 1.0)." }
        ],
        codeExamples: {
          curl: "curl https://api.openai.com/v1/chat/completions \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer $OPENAI_API_KEY\" \\\n  -d '{\n    \"model\": \"gpt-4o\",\n    \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}]\n  }'",
          python: "from openai import OpenAI\nclient = OpenAI()\n\ncompletion = client.chat.completions.create(\n  model=\"gpt-4o\",\n  messages=[{\"role\": \"user\", \"content\": \"Hello!\"}]\n)",
          javascript: "import OpenAI from \"openai\";\nconst openai = new OpenAI();\n\nconst completion = await openai.chat.completions.create({\n  model: \"gpt-4o\",\n  messages: [{ role: \"user\", content: \"Hello!\" }],\n});",
          go: "package main\nimport (\n  \"context\"\n  \"fmt\"\n  \"github.com/sashabaranov/go-openai\"\n)\n\nfunc main() {\n  client := openai.NewClient(\"YOUR_API_KEY\")\n  resp, _ := client.CreateChatCompletion(\n    context.Background(),\n    openai.ChatCompletionRequest{\n      Model: openai.GPT4o,\n      Messages: []openai.ChatCompletionMessage{\n        {Role: openai.ChatMessageRoleUser, Content: \"Hello!\"},\n      },\n    },\n  )\n  fmt.Println(resp.Choices[0].Message.Content)\n}"
        },
        response: {
          status: 200,
          body: {
            id: "chatcmpl-123",
            object: "chat.completion",
            created: 1677652288,
            model: "gpt-4o",
            choices: [{
              index: 0,
              message: {
                role: "assistant",
                content: "Hello! How can I assist you today?"
              },
              finish_reason: "stop"
            }],
            usage: {
              prompt_tokens: 9,
              completion_tokens: 12,
              total_tokens: 21
            }
          }
        }
      }
    ],
    recipes: [
      {
        title: "FastAPI Streaming SSE LLM Response",
        framework: "FastAPI",
        duration: "10 mins",
        difficulty: "Medium",
        diagram: `
+------------+       POST client query       +-----------------+
|   Client   | ----------------------------> | FastAPI Backend |
+------------+                               +-----------------+
      ^                                               |
      | SSE stream chunks                             v Stream tokens
      +----------------------------------------- [ OpenAI client API ]
`,
        code: `from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from openai import AsyncOpenAI

app = FastAPI()
client = AsyncOpenAI()

@app.post("/stream")
async def stream_chat(user_prompt: str):
    async def event_generator():
        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": user_prompt}],
            stream=True
        )
        async for chunk in response:
            content = chunk.choices[0].delta.content or ""
            if content:
                yield f"data: {content}\\n\\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")`
      }
    ],
    paths: [
      { id: "15m", name: "First Chat Completion", progress: 0, steps: ["Install client library", "Export API key", "Call gpt-4o API with prompt"] },
      { id: "3h", name: "Autonomous Agent Tool Calling", progress: 0, steps: ["Define local function JSON schemas", "Bind tools to chat completion call", "Execute returned tool call lists, feed back states"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [360, 350, 340, 335, 345, 340, 330],
      uptime: [99.82, 99.88, 99.85, 99.84, 99.89, 99.91, 99.85],
      errors: [0.24, 0.18, 0.15, 0.22, 0.19, 0.11, 0.14]
    }
  },
  {
    id: "github",
    name: "GitHub",
    logoColor: "#181717",
    category: "DevOps",
    verified: true,
    tagline: "The world's leading developer platform rest and graph APIs",
    description: "Manage repositories, pull requests, issues, projects, and users programmatically. Provides powerful hooks and webhooks to integrate automated workflows.",
    docsUrl: "https://docs.github.com/en/rest",
    githubUrl: "https://github.com/octokit/octokit.js",
    openapiUrl: "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/ghes-3.8/ghes-3.8.yaml",
    postmanUrl: "https://www.postman.com/github-api",
    sandboxAvailable: true,
    baseUrl: "https://api.github.com",
    vitals: {
      healthScore: 99.7,
      latency: 148,
      uptime: 99.95,
      docsScore: 9.0,
      sdkScore: 9.3,
      communityScore: 9.8,
      githubActivity: "Extreme (140 commits/week)",
      status: "Operational",
      responseTime: "148ms (p95: 220ms)",
      popularity: 97,
      security: "OAuth2 scoping, fine-grained access tokens",
      community: "Millions of users, extensive stack exchange answers",
      aiConfidence: 94,
      lastUpdated: "12 mins ago",
      commitsCount: "125,482",
      version: "2022-11-28",
      rateLimit: "5,000 requests/hour",
      authType: "Personal Access Token / OAuth",
      responseFormat: "JSON",
      difficulty: "Easy"
    },
    dna: {
      similarities: [
        { target: "gitlab", percentage: 86, reason: "Identical concepts of projects, merge requests, issues but path structure differs." }
      ],
      radar: {
        auth: 88,
        performance: 89,
        docs: 94,
        dx: 93,
        pricing: 95
      },
      migrationComplexity: "Low",
      breakingChangesPredictor: 0.8,
      evolutionTimeline: [
        { date: "May 2026", event: "Mandated fine-grained tokens for organization access." },
        { date: "Feb 2026", event: "Added rulesets configuration endpoints." }
      ],
      sdkMaturity: "Platinum (Official Octokit libraries in JavaScript, Ruby, .NET, Go)",
      deprecationRisk: "Low"
    },
    painIndex: {
      githubIssues: 54,
      stackoverflowQuestions: 12400,
      discordMentions: 110,
      redditActivity: "Medium (r/github)",
      learningDifficulty: "Easy",
      topComplaints: [
        "Rate limiting is tied strictly to token context, leading to lockouts during batch scraping.",
        "GraphQL endpoint schema is massive and sometimes times out on heavy tree fetches."
      ],
      confusingEndpoints: [
        { path: "/repos/{owner}/{repo}/contents/{path}", complexity: "Writing files via this REST endpoint requires passing the base64 encoded string AND the previous file SHA." }
      ],
      commonErrors: [
        {
          code: "bad_credentials",
          description: "The authentication token is either expired, missing scope permissions, or incorrect.",
          remedy: "Re-generate personal access token. Verify headers contain 'Authorization: Bearer <TOKEN>'."
        }
      ]
    },
    endpoints: [
      {
        path: "/repos/{owner}/{repo}/issues",
        method: "POST",
        description: "Creates an issue in the specified repository. Organization-wide permissions apply.",
        authRequired: true,
        rateLimit: "5,000 req/hour",
        params: [
          { name: "title", type: "string", required: true, description: "The title of the issue." },
          { name: "body", type: "string", required: false, description: "The contents of the issue in markdown." },
          { name: "labels", type: "array", required: false, description: "Names of labels to associate with this issue." }
        ],
        codeExamples: {
          curl: "curl -X POST -H \"Accept: application/vnd.github+json\" \\\n  -H \"Authorization: Bearer <TOKEN>\" \\\n  https://api.github.com/repos/octocat/hello-world/issues \\\n  -d '{\"title\":\"Found a bug\",\"body\":\"Something went wrong\"}'",
          python: "import requests\nheaders = {\"Authorization\": \"Bearer <TOKEN>\", \"Accept\": \"application/vnd.github+json\"}\nresp = requests.post(\n  \"https://api.github.com/repos/octocat/hello-world/issues\",\n  json={\"title\": \"Found a bug\", \"body\": \"Something went wrong\"},\n  headers=headers\n)",
          javascript: "import { Octokit } from \"octokit\";\nconst octokit = new Octokit({ auth: 'TOKEN' });\n\nawait octokit.request('POST /repos/{owner}/{repo}/issues', {\n  owner: 'octocat',\n  repo: 'hello-world',\n  title: 'Found a bug',\n  body: 'Something went wrong'\n});",
          go: "package main\nimport (\n  \"context\"\n  \"github.com/google/go-github/v45/github\"\n  \"golang.org/x/oauth2\"\n)\nfunc main() {\n  ctx := context.Background()\n  ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: \"TOKEN\"})\n  tc := oauth2.NewClient(ctx, ts)\n  client := github.NewClient(tc)\n  issue := &github.IssueRequest{Title: github.String(\"Found a bug\")}\n  client.Issues.Create(ctx, \"octocat\", \"hello-world\", issue)\n}"
        },
        response: {
          status: 201,
          body: {
            id: 1,
            number: 1347,
            title: "Found a bug",
            body: "Something went wrong",
            state: "open",
            user: {
              login: "octocat",
              id: 1
            }
          }
        }
      }
    ],
    recipes: [
      {
        title: "Github Issue Syncing Script",
        framework: "Node.js",
        duration: "5 mins",
        difficulty: "Easy",
        diagram: `
+---------------+           Listen for Webhooks          +--------------------+
|  GitHub Repo  | -------------------------------------> | Sync Handler (Node)|
+---------------+                                        +--------------------+
                                                                    |
                                                            upsert issues to DB
                                                                    v
                                                            notify Slack room
`,
        code: `const { Octokit } = require("octokit");
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function syncIssues() {
  const issues = await octokit.paginate("GET /repos/{owner}/{repo}/issues", {
    owner: "facebook",
    repo: "react",
    state: "open",
  });
  
  for (const issue of issues) {
    console.log(\`#\${issue.number}: \${issue.title}\`);
    // Write database syncer logics here
  }
}
syncIssues();`
      }
    ],
    paths: [
      { id: "15m", name: "Read Repo Information", progress: 0, steps: ["Initialize Octokit client", "Query repository details", "Print open issues count"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [154, 150, 148, 149, 147, 148, 146],
      uptime: [100, 100, 99.96, 99.99, 99.99, 100, 100],
      errors: [0.01, 0.01, 0.03, 0.01, 0.01, 0.01, 0.01]
    }
  },
  {
    id: "clerk",
    name: "Clerk",
    logoColor: "#6C47FF",
    category: "Authentication",
    verified: true,
    tagline: "More than authentication. Complete user management APIs",
    description: "Drop-in login boxes, multi-tenant workspace setups, account management controls, and session hooks for Next.js, React, and backend API platforms.",
    docsUrl: "https://clerk.com/docs/reference/backend-api",
    githubUrl: "https://github.com/clerk/clerk-sdk-go",
    openapiUrl: "https://raw.githubusercontent.com/clerk/clerk-openapi/main/openapi.yaml",
    postmanUrl: "https://www.postman.com/clerk-dev",
    sandboxAvailable: true,
    baseUrl: "https://api.clerk.com/v1",
    vitals: {
      healthScore: 99.9,
      latency: 48,
      uptime: 99.99,
      docsScore: 9.5,
      sdkScore: 9.7,
      communityScore: 9.4,
      githubActivity: "High (18 commits/week)",
      status: "Operational",
      responseTime: "48ms (p95: 78ms)",
      popularity: 91,
      security: "SOC2 compliance, encrypted session caches",
      community: "12k Github Stars, active Discord developer group",
      aiConfidence: 97,
      lastUpdated: "1 hour ago",
      commitsCount: "4,242",
      version: "2021-02-05",
      rateLimit: "600 requests/minute",
      authType: "Bearer Token (Secret Key)",
      responseFormat: "JSON",
      difficulty: "Easy"
    },
    dna: {
      similarities: [
        { target: "auth0", percentage: 82, reason: "JWT validation and tenant profile synchronization patterns are very similar, but Clerk wraps SDK hooks." }
      ],
      radar: {
        auth: 99,
        performance: 96,
        docs: 95,
        dx: 98,
        pricing: 78
      },
      migrationComplexity: "Low",
      breakingChangesPredictor: 1.5,
      evolutionTimeline: [
        { date: "June 2026", event: "Launched native passkey enrollment hooks." }
      ],
      sdkMaturity: "Platinum (Includes react hooks, middleware engines, and server components)",
      deprecationRisk: "Low"
    },
    painIndex: {
      githubIssues: 22,
      stackoverflowQuestions: 420,
      discordMentions: 180,
      redditActivity: "Low (some discussions in Next.js subreddits)",
      learningDifficulty: "Very Easy",
      topComplaints: [
        "Edge middleware parsing on cold-starts has minor latency overhead in isolated environments.",
        "Customizing themes deep in CSS classes is tricky in earlier SDK versions."
      ],
      confusingEndpoints: [
        { path: "/users/{user_id}/metadata", complexity: "Requires distinct parameters for public_metadata, private_metadata, and unsafe_metadata." }
      ],
      commonErrors: [
        {
          code: "resource_not_found",
          description: "The specified user_id or organization_id does not exist.",
          remedy: "Verify keys correspond to correct environment (production vs development)."
        }
      ]
    },
    endpoints: [
      {
        path: "/users",
        method: "GET",
        description: "Retrieves a list of users, sorted by creation date descending.",
        authRequired: true,
        rateLimit: "600 req/min",
        params: [
          { name: "limit", type: "integer", required: false, description: "Limit response count (default 10, max 500)." },
          { name: "offset", type: "integer", required: false, description: "Number of users to skip." }
        ],
        codeExamples: {
          curl: "curl -H \"Authorization: Bearer CLERK_SECRET_KEY\" \\\n  https://api.clerk.com/v1/users?limit=5",
          python: "import requests\nheaders = {\"Authorization\": \"Bearer CLERK_SECRET_KEY\"}\nr = requests.get(\"https://api.clerk.com/v1/users\", headers=headers, params={\"limit\": 5})",
          javascript: "import { createClerkClient } from '@clerk/backend';\nconst clerk = createClerkClient({ secretKey: 'SECRET' });\nconst users = await clerk.users.getUserList({ limit: 5 });",
          go: "package main\nimport (\n  \"fmt\"\n  \"github.com/clerk/clerk-sdk-go/v2\"\n  \"github.com/clerk/clerk-sdk-go/v2/user\"\n)\nfunc main() {\n  clerk.SetKey(\"SECRET\")\n  list, _ := user.List(clerk.ListParams{Limit: clerk.Int(5)})\n  fmt.Println(list.Users)\n}"
        },
        response: {
          status: 200,
          body: [
            {
              id: "user_2T2n8v1C",
              first_name: "John",
              last_name: "Doe",
              email_addresses: [{ email_address: "john@example.com" }],
              created_at: 1716912399
            }
          ]
        }
      }
    ],
    recipes: [
      {
        title: "Session JWT Validation in Express Backend",
        framework: "Express",
        duration: "5 mins",
        difficulty: "Easy",
        diagram: `
+------------+          Fetch dynamic data w/ JWT          +-----------------+
|   Client   | ------------------------------------------> | Express Backend |
+------------+                                             +-----------------+
                                                                    |
                                                         Validate JWT locally
                                                         w/ Clerk Public Keys
                                                                    v
                                                           Serve Secure JSON
`,
        code: `const jwt = require("jsonwebtoken");
const CLERK_PEM = process.env.CLERK_JWT_PUBLIC_KEY;

function checkClerkAuth(req, res, next) {
  const token = req.headers.authorization?.split(" ")[1];
  if (!token) return res.status(401).json({ error: "No token provided" });

  try {
    const decoded = jwt.verify(token, CLERK_PEM);
    req.auth = { userId: decoded.sub };
    next();
  } catch (err) {
    return res.status(403).json({ error: "Invalid session token" });
  }
}`
      }
    ],
    paths: [
      { id: "15m", name: "Next.js Authentication setup", progress: 0, steps: ["Install clerk/nextjs SDK", "Wrap layout with ClerkProvider", "Deploy Middleware rule to restrict endpoints"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [49, 48, 48, 48, 47, 48, 48],
      uptime: [100, 100, 100, 99.99, 100, 100, 100],
      errors: [0.01, 0, 0.01, 0.01, 0, 0, 0.01]
    }
  },
  {
    id: "twilio",
    name: "Twilio",
    logoColor: "#F22F46",
    category: "Communication",
    verified: true,
    tagline: "API interfaces for SMS, voice, video, and multi-channel verification",
    description: "Integrate programmable telecom channels directly inside backend servers. Deliver verification codes, handle phone call routing trees, and manage outbound campaigns globally.",
    docsUrl: "https://www.twilio.com/docs/usage/api",
    githubUrl: "https://github.com/twilio/twilio-node",
    openapiUrl: "https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/yaml/twilio_api_v2010.yaml",
    postmanUrl: "https://www.postman.com/twilio-api",
    sandboxAvailable: true,
    baseUrl: "https://api.twilio.com/2010-04-01",
    vitals: {
      healthScore: 97.8,
      latency: 120,
      uptime: 99.9,
      docsScore: 8.2,
      sdkScore: 8.5,
      communityScore: 9.0,
      githubActivity: "Medium (10 commits/week)",
      status: "Operational",
      responseTime: "120ms (excludes network gateway)",
      popularity: 88,
      security: "Basic auth (Account SID), webhook signature hashes",
      community: "Extensive developer footprint since 2008",
      aiConfidence: 91,
      lastUpdated: "4 hours ago",
      commitsCount: "22,504",
      version: "2010-04-01",
      rateLimit: "100 concurrent requests (queue-based)",
      authType: "Basic Auth (SID & Token)",
      responseFormat: "XML/JSON (JSON via suffix)",
      difficulty: "Medium"
    },
    dna: {
      similarities: [
        { target: "messagebird", percentage: 78, reason: "SMS sending and message queue architectures follow similar structures, but routing hooks differ." }
      ],
      radar: {
        auth: 80,
        performance: 82,
        docs: 85,
        dx: 86,
        pricing: 70
      },
      migrationComplexity: "Medium",
      breakingChangesPredictor: 0.5,
      evolutionTimeline: [
        { date: "Jan 2026", event: "Mandated 10DLC registration compliance fields." }
      ],
      sdkMaturity: "Gold (SDK wrappers in Node, C#, Java, Python, PHP, Ruby)",
      deprecationRisk: "Low (API contracts preserved for over a decade)"
    },
    painIndex: {
      githubIssues: 68,
      stackoverflowQuestions: 8420,
      discordMentions: 50,
      redditActivity: "Medium (r/twilio)",
      learningDifficulty: "Medium",
      topComplaints: [
        "Errors are returned with nested links to specific Twilio code-docs rather than standard JSON objects.",
        "A2P 10DLC compliance verification slows down active phone number acquisition."
      ],
      confusingEndpoints: [
        { path: "/Accounts/{AccountSid}/Messages.json", complexity: "Requires combining body with parameters like From and To, parsing media URLs correctly." }
      ],
      commonErrors: [
        {
          code: "21608",
          description: "The 'To' number is not verified in trial accounts.",
          remedy: "Verify destination number in Twilio console, or upgrade to a paid account tier."
        }
      ]
    },
    endpoints: [
      {
        path: "/Accounts/{AccountSid}/Messages.json",
        method: "POST",
        description: "Sends an SMS message to a phone number. Uses Account SID path injection.",
        authRequired: true,
        rateLimit: "100 concurrency limit",
        params: [
          { name: "To", type: "string", required: true, description: "The destination phone number in E.164 format (e.g., +15017122661)." },
          { name: "From", type: "string", required: true, description: "The Twilio phone number authorized to send this message." },
          { name: "Body", type: "string", required: true, description: "The text of the message you want to send, up to 1600 characters." }
        ],
        codeExamples: {
          curl: "curl -X POST https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json \\\n  --data-urlencode \"To=+15017122661\" \\\n  --data-urlencode \"From=+15558675309\" \\\n  --data-urlencode \"Body=Hello!\" \\\n  -u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN",
          python: "from twilio.rest import Client\nclient = Client(\"SID\", \"TOKEN\")\nmessage = client.messages.create(\n  to=\"+15017122661\",\n  from_=\"+15558675309\",\n  body=\"Hello!\"\n)",
          javascript: "const client = require('twilio')('SID', 'TOKEN');\nclient.messages.create({\n  to: '+15017122661',\n  from: '+15558675309',\n  body: 'Hello!'\n});",
          go: "package main\nimport (\n  \"fmt\"\n  \"github.com/twilio/twilio-go\"\n  openapi \"github.com/twilio/twilio-go/rest/api/v2010\"\n)\nfunc main() {\n  client := twilio.NewRestClientWithParams(twilio.ClientParams{Username: \"SID\", Password: \"TOKEN\"})\n  params := &openapi.CreateMessageParams{}\n  params.SetTo(\"+15017122661\")\n  params.SetFrom(\"+15558675309\")\n  params.SetBody(\"Hello!\")\n  resp, _ := client.Api.CreateMessage(params)\n  fmt.Println(resp.Sid)\n}"
        },
        response: {
          status: 201,
          body: {
            sid: "SM800h1n29Ak2",
            date_created: "Thu, 30 Jul 2026 20:00:00 +0000",
            to: "+15017122661",
            from: "+15558675309",
            body: "Hello!",
            status: "queued"
          }
        }
      }
    ],
    recipes: [
      {
        title: "2FA Verification Route using Twilio Verify",
        framework: "Node.js",
        duration: "10 mins",
        difficulty: "Medium",
        diagram: `
+---------------+           Request OTP via SMS           +--------------------+
|  User Client  | --------------------------------------> | Verify Endpoint    |
+---------------+                                         +--------------------+
                                                                    |
                                                          Triggers Twilio Verify
                                                                    v
                                                          Send OTP code to Phone
`,
        code: `const client = require('twilio')(process.env.TWILIO_SID, process.env.TWILIO_TOKEN);

async function sendOTP(phoneNumber) {
  const verification = await client.verify.v2.services(process.env.VERIFY_SERVICE_SID)
    .verifications
    .create({ to: phoneNumber, channel: 'sms' });
  return verification.status;
}

async function checkOTP(phoneNumber, code) {
  const check = await client.verify.v2.services(process.env.VERIFY_SERVICE_SID)
    .verificationChecks
    .create({ to: phoneNumber, code: code });
  return check.status === 'approved';
}`
      }
    ],
    paths: [
      { id: "15m", name: "Send First SMS", progress: 0, steps: ["Acquire phone number", "Configure credentials", "Dispatch Outbound Request"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [124, 122, 120, 118, 121, 120, 119],
      uptime: [99.9, 99.88, 99.92, 99.9, 99.9, 99.91, 99.9],
      errors: [0.08, 0.09, 0.05, 0.07, 0.06, 0.04, 0.05]
    }
  },
  {
    id: "razorpay",
    name: "Razorpay",
    logoColor: "#0B72E7",
    category: "Payments",
    verified: true,
    tagline: "Converged payments infrastructure for modern Indian businesses",
    description: "Indian payment gateway offering full support for credit cards, local banks, UPI, instant checkout frames, subscription management, and auto-routing features.",
    docsUrl: "https://razorpay.com/docs/api",
    githubUrl: "https://github.com/razorpay/razorpay-node",
    openapiUrl: "https://raw.githubusercontent.com/razorpay/openapi/master/openapi.yaml",
    postmanUrl: "https://www.postman.com/razorpay-api",
    sandboxAvailable: true,
    baseUrl: "https://api.razorpay.com/v1",
    vitals: {
      healthScore: 98.9,
      latency: 78,
      uptime: 99.9,
      docsScore: 8.9,
      sdkScore: 8.8,
      communityScore: 9.1,
      githubActivity: "High (15 commits/week)",
      status: "Operational",
      responseTime: "78ms (p95: 110ms)",
      popularity: 89,
      security: "PCI-DSS compliance, UPI network integrations",
      community: "Largest business footprint in Indian tech startups",
      aiConfidence: 94,
      lastUpdated: "3 hours ago",
      commitsCount: "4,902",
      version: "v1 (continuous integrations)",
      rateLimit: "50 requests/second",
      authType: "Basic Auth (Key & Secret)",
      responseFormat: "JSON",
      difficulty: "Medium"
    },
    dna: {
      similarities: [
        { target: "stripe", percentage: 89, reason: "REST schemas, entity mappings (Orders, Payments), and status states parallel Stripe closely." }
      ],
      radar: {
        auth: 88,
        performance: 94,
        docs: 89,
        dx: 88,
        pricing: 92
      },
      migrationComplexity: "Low (direct mapping maps parameters from stripe)",
      breakingChangesPredictor: 1.8,
      evolutionTimeline: [
        { date: "May 2026", event: "Migrated UPI recurring subscriptions to RBI e-mandate v2 schemas." }
      ],
      sdkMaturity: "Gold (Official wrappers in Node, PHP, Python, Java, Go, C#)",
      deprecationRisk: "Low"
    },
    painIndex: {
      githubIssues: 56,
      stackoverflowQuestions: 1820,
      discordMentions: 90,
      redditActivity: "Medium (r/developersIndia)",
      learningDifficulty: "Medium",
      topComplaints: [
        "RBI regulatory directives can trigger rapid updates to auto-debit validation rules.",
        "Error codes are occasionally general and require manual console check."
      ],
      confusingEndpoints: [
        { path: "/orders", complexity: "A payment cannot be collected directly. You must create an Order entity first, then pass its ID to the checkout layer." }
      ],
      commonErrors: [
        {
          code: "bad_request_error",
          description: "Required fields are missing, or format validation failed.",
          remedy: "Verify currency is INR. Amounts must be represented in paisa (100 for ₹1.00)."
        }
      ]
    },
    endpoints: [
      {
        path: "/orders",
        method: "POST",
        description: "Creates an order entity. Highly recommended to bind payments with order entities to ensure auto-capture consistency.",
        authRequired: true,
        rateLimit: "50 req/sec",
        params: [
          { name: "amount", type: "integer", required: true, description: "The amount to be paid in small currency units (e.g. 50000 for ₹500.00)." },
          { name: "currency", type: "string", required: true, description: "Three-letter ISO currency code (INR is standard)." },
          { name: "receipt", type: "string", required: false, description: "Your custom ledger identifier." }
        ],
        codeExamples: {
          curl: "curl -u key_id:key_secret -X POST https://api.razorpay.com/v1/orders \\\n  -H 'content-type: application/json' \\\n  -d '{\"amount\":50000,\"currency\":\"INR\",\"receipt\":\"receipt#1\"}'",
          python: "import razorpay\nclient = razorpay.Client(auth=(\"key_id\", \"key_secret\"))\nclient.order.create({\n  \"amount\": 50000,\n  \"currency\": \"INR\",\n  \"receipt\": \"receipt#1\"\n})",
          javascript: "const Razorpay = require('razorpay');\nvar instance = new Razorpay({ key_id: 'YOUR_KEY_ID', key_secret: 'YOUR_KEY_SECRET' });\n\nconst order = await instance.orders.create({\n  amount: 50000,\n  currency: \"INR\",\n  receipt: \"receipt#1\"\n});",
          go: "package main\nimport (\n  \"fmt\"\n  \"github.com/razorpay/razorpay-go\"\n)\nfunc main() {\n  client := razorpay.NewClient(\"key_id\", \"key_secret\")\n  data := map[string]interface{}{\n    \"amount\":   50000,\n    \"currency\": \"INR\",\n    \"receipt\":  \"receipt#1\",\n  }\n  body, _ := client.Order.Create(data, nil)\n  fmt.Println(body)\n}"
        },
        response: {
          status: 200,
          body: {
            id: "order_DBJ2nx18nAk2",
            entity: "order",
            amount: 50000,
            currency: "INR",
            receipt: "receipt#1",
            status: "created",
            created_at: 1716912411
          }
        }
      }
    ],
    recipes: [
      {
        title: "Razorpay Checkout Handshake Verification",
        framework: "FastAPI",
        duration: "5 mins",
        difficulty: "Easy",
        diagram: `
+---------------+           Pass Payment Hash            +--------------------+
| Client App    | -------------------------------------> | FastAPI Backend    |
+---------------+                                         +--------------------+
                                                                    |
                                                          Compute signature hash
                                                          using SHA256 secret
                                                                    v
                                                            Update DB Order Status
`,
        code: `import hmac
import hashlib
from fastapi import FastAPI, HTTPException

app = FastAPI()
RAZORPAY_SECRET = "YOUR_KEY_SECRET"

@app.post("/verify")
def verify_payment(order_id: str, payment_id: str, signature: str):
    msg = f"{order_id}|{payment_id}".encode()
    generated_sig = hmac.new(
        RAZORPAY_SECRET.encode(),
        msg,
        hashlib.sha256
    ).hexdigest()

    if not hmac.compare_digest(generated_sig, signature):
        raise HTTPException(status_code=400, detail="Invalid signature verification")
    
    return {"status": "success", "message": "Payment verified"}
`
      }
    ],
    paths: [
      { id: "15m", name: "Accept Payments in React", progress: 0, steps: ["Create Order via server backend", "Trigger checkout modal flow", "Verify signature on server webhook"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [80, 79, 78, 77, 80, 78, 78],
      uptime: [99.9, 99.9, 99.88, 99.9, 99.91, 99.9, 99.9],
      errors: [0.03, 0.02, 0.04, 0.02, 0.03, 0.02, 0.02]
    }
  },
  {
    id: "paypal",
    name: "PayPal",
    logoColor: "#003087",
    category: "Payments",
    verified: true,
    tagline: "Global payment ledger processing networks",
    description: "Standard checkout frameworks, recurring invoice flows, dispute resolution APIs, and balance ledger controllers for enterprise-scale global operations.",
    docsUrl: "https://developer.paypal.com/docs/api",
    githubUrl: "https://github.com/paypal/paypal-checkout-components",
    openapiUrl: "https://raw.githubusercontent.com/paypal/openapi/master/openapi.yaml",
    postmanUrl: "https://www.postman.com/paypal-developer",
    sandboxAvailable: true,
    baseUrl: "https://api-m.sandbox.paypal.com",
    vitals: {
      healthScore: 95.8,
      latency: 240,
      uptime: 99.88,
      docsScore: 7.5,
      sdkScore: 7.8,
      communityScore: 8.9,
      githubActivity: "Low (2 commits/week)",
      status: "Operational",
      responseTime: "240ms (p95: 390ms)",
      popularity: 84,
      security: "OAuth2 authentication scopes, multi-factor accounts",
      community: "Pioneer in online transaction layers",
      aiConfidence: 85,
      lastUpdated: "1 day ago",
      commitsCount: "18,480",
      version: "v2 (pinned upgrades)",
      rateLimit: "20 requests/second",
      authType: "OAuth2 (Client Credentials)",
      responseFormat: "JSON",
      difficulty: "Hard"
    },
    dna: {
      similarities: [
        { target: "stripe", percentage: 67, reason: "Both handle merchant payouts, but PayPal uses distinct access token lifecycles and order-capture handshakes." }
      ],
      radar: {
        auth: 72,
        performance: 65,
        docs: 70,
        dx: 72,
        pricing: 80
      },
      migrationComplexity: "High (distinct token handshakes and capture flows)",
      breakingChangesPredictor: 2.2,
      evolutionTimeline: [
        { date: "March 2026", event: "Completed global transition to OAuth2 v2 tokens." }
      ],
      sdkMaturity: "Silver (Legacy SDK wrappers exist, now directing devs to direct REST request integrations)",
      deprecationRisk: "Low"
    },
    painIndex: {
      githubIssues: 104,
      stackoverflowQuestions: 14820,
      discordMentions: 12,
      redditActivity: "High (mainly payment dispute queries)",
      learningDifficulty: "High",
      topComplaints: [
        "SDK wrappers are deprecated in favor of raw HTTP queries, requiring manual access-token lifecycle management.",
        "Error codes are highly nested and combine different scopes (e.g. ISSUE_PREVENTING_CAPTURE vs general validation errors)."
      ],
      confusingEndpoints: [
        { path: "/v2/checkout/orders", complexity: "Requires separate authentication token fetch. Access tokens must be dynamically rotated every 9 hours." }
      ],
      commonErrors: [
        {
          code: "UNPROCESSABLE_ENTITY",
          description: "The payment entity validation failed, or balance was insufficient.",
          remedy: "Check checkout request payload. Ensure currency codes align with recipient account config."
        }
      ]
    },
    endpoints: [
      {
        path: "/v2/checkout/orders",
        method: "POST",
        description: "Creates an order that will act as the transaction container. Complete payment capture via order intent confirmation.",
        authRequired: true,
        rateLimit: "20 req/sec",
        params: [
          { name: "intent", type: "string", required: true, description: "The intent to either AUTHORIZE or CAPTURE immediately." },
          { name: "purchase_units", type: "array", required: true, description: "An array of transaction details representing items or pricing models." }
        ],
        codeExamples: {
          curl: "curl -v -X POST https://api-m.sandbox.paypal.com/v2/checkout/orders \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Bearer <ACCESS_TOKEN>\" \\\n  -d '{\n    \"intent\": \"CAPTURE\",\n    \"purchase_units\": [{\"amount\": {\"currency_code\": \"USD\", \"value\": \"100.00\"}}]\n  }'",
          python: "import requests\nheaders = {\"Authorization\": \"Bearer <ACCESS_TOKEN>\", \"Content-Type\": \"application/json\"}\npayload = {\"intent\": \"CAPTURE\", \"purchase_units\": [{\"amount\": {\"currency_code\": \"USD\", \"value\": \"100.00\"}}]}\nresp = requests.post(\"https://api-m.sandbox.paypal.com/v2/checkout/orders\", json=payload, headers=headers)",
          javascript: "const response = await fetch('https://api-m.sandbox.paypal.com/v2/checkout/orders', {\n  method: 'POST',\n  headers: {\n    'Content-Type': 'application/json',\n    'Authorization': 'Bearer ' + ACCESS_TOKEN\n  },\n  body: JSON.stringify({\n    intent: 'CAPTURE',\n    purchase_units: [{ amount: { currency_code: 'USD', value: '100.00' } }]\n  })\n});",
          go: "package main\nimport (\n  \"bytes\"\n  \"net/http\"\n)\nfunc main() {\n  payload := []byte(\`{\"intent\":\"CAPTURE\",\"purchase_units\":[{\"amount\":{\"currency_code\":\"USD\",\"value\":\"100.00\"}}]}\`)\n  req, _ := http.NewRequest(\"POST\", \"https://api-m.sandbox.paypal.com/v2/checkout/orders\", bytes.NewBuffer(payload))\n  req.Header.Set(\"Authorization\", \"Bearer ACCESS_TOKEN\")\n  req.Header.Set(\"Content-Type\", \"application/json\")\n  client := &http.Client{}\n  client.Do(req)\n}"
        },
        response: {
          status: 201,
          body: {
            id: "5O40893072",
            status: "CREATED",
            intent: "CAPTURE",
            purchase_units: [{
              amount: { currency_code: "USD", value: "100.00" }
            }],
            links: [{
              href: "https://www.sandbox.paypal.com/checkoutnow?token=5O40893072",
              rel: "approve",
              method: "GET"
            }]
          }
        }
      }
    ],
    recipes: [
      {
        title: "PayPal Access Token Automatic Rotator",
        framework: "Node.js",
        duration: "10 mins",
        difficulty: "Medium",
        diagram: `
+--------------------+            GET oauth2/token            +--------------------+
| Next.js Auth loop  | -------------------------------------> | PayPal Auth Server |
+--------------------+                                        +--------------------+
          |                                                             |
    Check expiry                                                    Return JWT
    If expired, refresh token                                           |
          +<------------------------------------------------------------+
`,
        code: `let cachedToken = null;
let tokenExpiryTime = null;

async function getPayPalAccessToken() {
  if (cachedToken && tokenExpiryTime && Date.now() < tokenExpiryTime) {
    return cachedToken;
  }

  const credentials = Buffer.from(
    \`\${process.env.PAYPAL_CLIENT_ID}:\${process.env.PAYPAL_CLIENT_SECRET}\`
  ).toString("base64");

  const response = await fetch("https://api-m.sandbox.paypal.com/v1/oauth2/token", {
    method: "POST",
    headers: {
      Authorization: \`Basic \${credentials}\`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: "grant_type=client_credentials",
  });

  const data = await response.json();
  cachedToken = data.access_token;
  tokenExpiryTime = Date.now() + (data.expires_in - 300) * 1000; // cache with 5m headroom
  return cachedToken;
}`
      }
    ],
    paths: [
      { id: "15m", name: "Create OAuth client credential", progress: 0, steps: ["Register app on dashboard", "Acquire credentials pair", "Retrieve access token via CLI"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [250, 248, 240, 238, 244, 240, 239],
      uptime: [99.88, 99.88, 99.88, 99.89, 99.85, 99.88, 99.88],
      errors: [0.12, 0.1, 0.14, 0.11, 0.15, 0.12, 0.12]
    }
  },
  {
    id: "anthropic",
    name: "Anthropic",
    logoColor: "#E0B89C",
    category: "AI",
    verified: true,
    tagline: "Developer interfaces for Claude reasoning and chat models",
    description: "Connect to large context window models (Claude 3.5 Sonnet) featuring strong reasoning, advanced coding, tool parsing, and structured output formatting.",
    docsUrl: "https://docs.anthropic.com/claude/reference",
    githubUrl: "https://github.com/anthropics/anthropic-sdk-typescript",
    openapiUrl: "https://raw.githubusercontent.com/anthropics/openapi-spec/main/openapi.yaml",
    postmanUrl: "https://www.postman.com/anthropic-api",
    sandboxAvailable: false,
    baseUrl: "https://api.anthropic.com/v1",
    vitals: {
      healthScore: 98.8,
      latency: 310,
      uptime: 99.9,
      docsScore: 8.8,
      sdkScore: 9.0,
      communityScore: 9.6,
      githubActivity: "High (15 commits/week)",
      status: "Operational",
      responseTime: "310ms (p95: 520ms)",
      popularity: 95,
      security: "SOC2 compliance, no-training data privacy scopes",
      community: "Fastest-growing AI developer community",
      aiConfidence: 95,
      lastUpdated: "15 mins ago",
      commitsCount: "2,204",
      version: "2023-06-01",
      rateLimit: "4,000 requests/minute",
      authType: "Header Auth (x-api-key)",
      responseFormat: "JSON",
      difficulty: "Medium"
    },
    dna: {
      similarities: [
        { target: "openai", percentage: 91, reason: "Stream chunks and multi-turn message maps overlap closely. System prompt is sent as separate root parameter." }
      ],
      radar: {
        auth: 90,
        performance: 82,
        docs: 92,
        dx: 93,
        pricing: 88
      },
      migrationComplexity: "Medium (requires prompt alignment & schema validation)",
      breakingChangesPredictor: 3.5,
      evolutionTimeline: [
        { date: "June 2026", event: "Released Claude 3.5 Sonnet token caches." }
      ],
      sdkMaturity: "Gold (Official client wrappers in Node and Python)",
      deprecationRisk: "Moderate"
    },
    painIndex: {
      githubIssues: 45,
      stackoverflowQuestions: 840,
      discordMentions: 480,
      redditActivity: "High (r/claude)",
      learningDifficulty: "Medium",
      topComplaints: [
        "Prompt structure mandates using the 'x-api-key' header and specific anthropic-version headers.",
        "JSON output mode requires detailed system prompts to prevent formatting exceptions."
      ],
      confusingEndpoints: [
        { path: "/v1/messages", complexity: "System instructions must be specified in the root payload, not as a role in the message list." }
      ],
      commonErrors: [
        {
          code: "invalid_authorization",
          description: "Missing or invalid api key header configuration.",
          remedy: "Verify your headers include 'x-api-key' and 'anthropic-version: 2023-06-01'."
        }
      ]
    },
    endpoints: [
      {
        path: "/v1/messages",
        method: "POST",
        description: "Sends a request to Claude model, returning generated text or tool calls.",
        authRequired: true,
        rateLimit: "4,000 requests/min",
        params: [
          { name: "model", type: "string", required: true, description: "The model ID (e.g., claude-3-5-sonnet-20240620)." },
          { name: "messages", type: "array", required: true, description: "An array of message dictionaries (user, assistant roles)." },
          { name: "max_tokens", type: "integer", required: true, description: "Maximum tokens to generate." }
        ],
        codeExamples: {
          curl: "curl https://api.anthropic.com/v1/messages \\\n  -H \"x-api-key: $ANTHROPIC_API_KEY\" \\\n  -H \"anthropic-version: 2023-06-01\" \\\n  -H \"content-type: application/json\" \\\n  -d '{\n    \"model\": \"claude-3-5-sonnet-20240620\",\n    \"max_tokens\": 1024,\n    \"messages\": [{\"role\": \"user\", \"content\": \"Hello, Claude\"}]\n  }'",
          python: "import anthropic\nclient = anthropic.Anthropic()\n\nmessage = client.messages.create(\n  model=\"claude-3-5-sonnet-20240620\",\n  max_tokens=1024,\n  messages=[{\"role\": \"user\", \"content\": \"Hello, Claude\"}]\n)",
          javascript: "import Anthropic from '@anthropic-ai/sdk';\nconst anthropic = new Anthropic();\n\nconst message = await anthropic.messages.create({\n  model: \"claude-3-5-sonnet-20240620\",\n  max_tokens: 1024,\n  messages: [{ role: \"user\", content: \"Hello, Claude\" }],\n});",
          go: "package main\nimport (\n  \"context\"\n  \"fmt\"\n  \"github.com/liushuangls/go-anthropic/v2\"\n)\nfunc main() {\n  client := anthropic.NewClient(\"TOKEN\")\n  resp, _ := client.CreateMessages(context.Background(), anthropic.MessagesRequest{\n    Model:     anthropic.ModelClaude35Sonnet20240620,\n    MaxTokens: 1024,\n    Messages: []anthropic.Message{\n      {Role: anthropic.RoleUser, Content: []anthropic.MessageContent{{Type: anthropic.ContentTypeText, Text: \"Hello, Claude\"}}},\n    },\n  })\n  fmt.Println(resp.Content[0].Text)\n}"
        },
        response: {
          status: 200,
          body: {
            id: "msg_01n8A2kn1G",
            type: "message",
            role: "assistant",
            content: [{
              type: "text",
              text: "Hello! It is a pleasure to meet you. How can I help you today?"
            }],
            model: "claude-3-5-sonnet-20240620",
            usage: {
              input_tokens: 12,
              output_tokens: 18
            }
          }
        }
      }
    ],
    recipes: [
      {
        title: "Claude Prompt Cache Helper",
        framework: "Next.js",
        duration: "5 mins",
        difficulty: "Medium",
        diagram: `
+------------+       Send conversation + system docs      +-----------------+
| Next.js    | -----------------------------------------> | Claude API      |
+------------+                                            +-----------------+
                                                                   |
                                                         Evaluate cache token matches
                                                         Cache HIT -> save cost & latency
                                                                   v
                                                          Generate response
`,
        code: `import Anthropic from "@anthropic-ai/sdk";
const client = new Anthropic();

async function callClaudeCached(messages, systemDocument) {
  return await client.beta.promptCaching.messages.create({
    model: "claude-3-5-sonnet-20240620",
    max_tokens: 1024,
    system: [
      {
        type: "text",
        text: systemDocument,
        cache_control: { type: "ephemeral" } // Tells Anthropic to cache this system prompt
      }
    ],
    messages: messages,
  });
}`
      }
    ],
    paths: [
      { id: "15m", name: "Claude API Integration", progress: 0, steps: ["Acquire developer key", "Set version headers", "Deliver basic user request"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [330, 320, 310, 305, 315, 310, 305],
      uptime: [99.9, 99.9, 99.88, 99.9, 99.9, 99.92, 99.9],
      errors: [0.08, 0.05, 0.04, 0.06, 0.05, 0.03, 0.04]
    }
  },
  {
    id: "auth0",
    name: "Auth0",
    logoColor: "#EB5424",
    category: "Authentication",
    verified: true,
    tagline: "Enterprise identity provider and single sign-on APIs",
    description: "Federated login hubs, custom database connection drivers, legacy application bridges, and OAuth2 security profiles for cross-platform applications.",
    docsUrl: "https://auth0.com/docs/api",
    githubUrl: "https://github.com/auth0/node-auth0",
    openapiUrl: "https://raw.githubusercontent.com/auth0/openapi/master/openapi.yaml",
    postmanUrl: "https://www.postman.com/auth0-api",
    sandboxAvailable: true,
    baseUrl: "https://auth0-tenant.us.auth0.com",
    vitals: {
      healthScore: 97.4,
      latency: 95,
      uptime: 99.99,
      docsScore: 8.0,
      sdkScore: 8.2,
      communityScore: 8.5,
      githubActivity: "Medium (5 commits/week)",
      status: "Operational",
      responseTime: "95ms (p95: 160ms)",
      popularity: 86,
      security: "ISO27001 compliance, federated login controls",
      community: "Industry standard identity controller since 2013",
      aiConfidence: 86,
      lastUpdated: "2 days ago",
      commitsCount: "14,902",
      version: "v2 (continuous integrations)",
      rateLimit: "100 requests/second",
      authType: "OAuth2 / Bearer Token",
      responseFormat: "JSON",
      difficulty: "Hard"
    },
    dna: {
      similarities: [
        { target: "clerk", percentage: 82, reason: "Both implement JWT token structures for tenant validation, but Auth0 handles heavier enterprise SAML integrations." }
      ],
      radar: {
        auth: 95,
        performance: 88,
        docs: 80,
        dx: 80,
        pricing: 72
      },
      migrationComplexity: "High (requires mapping database connections and user profiles)",
      breakingChangesPredictor: 1.1,
      evolutionTimeline: [
        { date: "May 2026", event: "Standardized actions middleware scripting engines." }
      ],
      sdkMaturity: "Gold (Official client wrappers in Node, React, Next, Angular, Go, Python, PHP, Ruby)",
      deprecationRisk: "Low"
    },
    painIndex: {
      githubIssues: 82,
      stackoverflowQuestions: 11420,
      discordMentions: 15,
      redditActivity: "Medium (r/auth0)",
      learningDifficulty: "High",
      topComplaints: [
        "Transitioning from legacy Rules/Hooks to dynamic Actions requires rewriting Node scripting interfaces.",
        "Pricing scales aggressively as monthly active users increase beyond basic tiers."
      ],
      confusingEndpoints: [
        { path: "/oauth/token", complexity: "Requires combining grant_type, client_id, client_secret, audience, and scopes in a single raw payload." }
      ],
      commonErrors: [
        {
          code: "invalid_client",
          description: "Client Credentials authentication failed (bad client secret or ID).",
          remedy: "Verify domain corresponds to client tenant. Double check client secret string in dash."
        }
      ]
    },
    endpoints: [
      {
        path: "/oauth/token",
        method: "POST",
        description: "Retrieves an access token using standard OAuth client credentials or authentication code grants.",
        authRequired: false,
        rateLimit: "100 req/sec",
        params: [
          { name: "grant_type", type: "string", required: true, description: "Type of token grant (e.g. client_credentials, authorization_code)." },
          { name: "client_id", type: "string", required: true, description: "The client ID of your Auth0 application." },
          { name: "client_secret", type: "string", required: true, description: "The client secret of your Auth0 application." }
        ],
        codeExamples: {
          curl: "curl -X POST https://auth0-tenant.us.auth0.com/oauth/token \\\n  -H \"content-type: application/x-www-form-urlencoded\" \\\n  -d \"grant_type=client_credentials&client_id=ID&client_secret=SECRET&audience=AUDIENCE\"",
          python: "import requests\npayload = {\"grant_type\":\"client_credentials\",\"client_id\":\"ID\",\"client_secret\":\"SECRET\",\"audience\":\"AUDIENCE\"}\nresp = requests.post(\"https://auth0-tenant.us.auth0.com/oauth/token\", data=payload)",
          javascript: "const response = await fetch('https://auth0-tenant.us.auth0.com/oauth/token', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n  body: new URLSearchParams({\n    grant_type: 'client_credentials',\n    client_id: 'ID',\n    client_secret: 'SECRET',\n    audience: 'AUDIENCE'\n  })\n});",
          go: "package main\nimport (\n  \"bytes\"\n  \"net/http\"\n)\nfunc main() {\n  payload := []byte(\"grant_type=client_credentials&client_id=ID&client_secret=SECRET\")\n  http.Post(\"https://auth0-tenant.us.auth0.com/oauth/token\", \"application/x-www-form-urlencoded\", bytes.NewBuffer(payload))\n}"
        },
        response: {
          status: 200,
          body: {
            access_token: "eyJhbGciOiJSUzI1NiIs...",
            scope: "read:users write:users",
            expires_in: 86400,
            token_type: "Bearer"
          }
        }
      }
    ],
    recipes: [
      {
        title: "Auth0 Custom Post-User Registration Action",
        framework: "Node.js",
        duration: "5 mins",
        difficulty: "Medium",
        diagram: `
+---------------+           Trigger Actions Flow           +--------------------+
| Auth0 Signup  | ---------------------------------------> | Custom Action code |
+---------------+                                          +--------------------+
                                                                    |
                                                          Send data to stripe API
                                                                    v
                                                          Update user metadata
`,
        code: `exports.onExecutePostUserRegistration = async (event, api) => {
  const stripe = require('stripe')(event.secrets.STRIPE_SECRET_KEY);
  
  try {
    const customer = await stripe.customers.create({
      email: event.user.email,
      name: event.user.name,
    });
    api.user.setAppMetadata("stripe_customer_id", customer.id);
  } catch (err) {
    console.log("Stripe customer creation failed: ", err.message);
  }
};`
      }
    ],
    paths: [
      { id: "15m", name: "Acquire OAuth Auth Token", progress: 0, steps: ["Configure tenant app", "Fetch client tokens via API", "Verify returned JWT permissions"] }
    ],
    analytics: {
      labels: ["01 Jul", "05 Jul", "10 Jul", "15 Jul", "20 Jul", "25 Jul", "30 Jul"],
      latency: [98, 96, 95, 94, 97, 95, 95],
      uptime: [99.99, 100, 99.98, 99.99, 99.99, 100, 99.99],
      errors: [0.02, 0.01, 0.02, 0.01, 0.02, 0.02, 0.01]
    }
  }
];

export const CATEGORIES = [
  "All",
  "Payments",
  "AI",
  "Authentication",
  "Communication",
  "DevOps"
];
